version: '3'
services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=applications
      - DB_USERNAME=fabio
      - DB_PASSWORD=Cliente@2008
    depends_on:
      - mysql

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Cliente@site
      MYSQL_DATABASE: applications
      MYSQL_USER: fabio
      MYSQL_PASSWORD: Cliente@2008
